name: RSS Recon

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # 【重要】GitHubにファイルを書き込む許可を与える
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install feedparser requests

      - name: Run RSS script
        run: python get_rss.py

      - name: Commit and Push results
        # 取得したデータ（ファイル）をGitHubに保存する処理
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update RSS results" || exit 0
          git push
